name: Multik CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Multik container
    - run: docker build --no-cache --progress=plain -t multik .
    - run: docker run -v ./results/:/results/ multik
