name: Multik CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build docker container
      run: docker build --no-cache --progress=plain -t multik ${{ github.workspace }}
    - name: Run container
      run: docker run -v ${{ github.workspace }}:/usr/src/multik  multik
